### ISSUE TITLE
false warnings about remote file changing?

### ISSUE THREAD

**Issue by jeswcollins** [cjohansson/emacs-ssh-deploy#53]
I've been getting warnings about the remote file changing, and asking me to ediff or download. I don't think file has actually changed. It appears the same. Maybe I am saving too many times too quickly in these cases?

Actually, I don't really mind these warnings, but the screen splits (horizontal) sometimes to display them. Can I disable that splitting?

Possibly related [issue](https://github.com/cjohansson/emacs-ssh-deploy/issues/42)

**Comment by cjohansson** [comment]
If you can navigate to any difference regions in ediff then there are actual differences, it could be white-space differences only and that is impossible to spot f you're not using `whitespace-mode`.

What can happen sometimes is that multiple asynchronous uploads finish in the wrong order, if the connection is slow, maybe your change 2 got uploaded before change 1 and this will make the plug-in think that change 1 is the latest revision even though change 2 was before it. So it's kind of a race condition issue.

In these cases, just uploading with force will solve the problem. If you press the ssh-deploy difference action and ediff is opened it means the files are actually different, otherwise you will just get a message in the mini-buffer that the files have identical contents.

Technically I don't think it's a bug but it is an issue that can happen in some cases with asynchronous uploads on a slow connection

**Comment by cjohansson** [comment]
Please let me know if you can reproduce the issue, I get it sometimes and I believe it's related to a race-condition happening with multiple asynchronous uploads of the same file. The latest revision is the latest uploaded contents so I think in some cases this gets out of sync. I am not sure how to solve that problem, maybe I could add a lock mechanism preventing more than one asynchronous operation on the same file at a time?

**Comment by cjohansson** [comment]
It uploads only files and not buffers, so if you upload a unsaved buffer (related to a file) it will actually upload the file in the last saved state.

The diff will also detect white-space differences so there can be non-visible differences in the files.

If you download the file first, before doing any edits, the issue should disappear. You can also force upload the file and it will discard differences.

There is also a global setting available to discard differences altogether
